Unhandled exception in thread started by <function thread_entry at 0x\[0-9a-f\]\+>
Traceback (most recent call last):
  File \.\+, line 6, in thread_entry
ValueError: 
done
